### ISSUE TITLE
Feature Request: NAT support for ipv6 (IP6TABLES) 

### ISSUE THREAD

**Issue by ghost** [franciscofranco/enchilada#1]
Hey Francisco,

I've made a post regarding this on XDA thread but as it's a mess there and it can be buried between the messages, I thought about opening an issue here. 

Is there a possibility to improve ip6tables to support nat on your kernel for r15 perhaps? 

Thank you :) 
![Screenshot_20190327-082319](https://user-images.githubusercontent.com/3320229/55067935-4e8b3b80-5089-11e9-8eb2-49598c043a1b.jpg)

**Comment by franciscofranco** [comment]
Should work on r15. Re-open this if it's not.

**Comment by ghost** [comment]
> Should work on r15. Re-open this if it's not.

![Screenshot_20190328-055311](https://user-images.githubusercontent.com/3320229/55129012-39acb780-511e-11e9-9032-95f75c345154.jpg)

@franciscofranco unfortunately it doesn't :(

And stupid Github doesn't allow me to reopen the issue :(

**Comment by franciscofranco** [comment]
Wtf. Do you know which Kernel config option is needed for IPV6 NAT?

**Comment by ghost** [comment]
> Wtf. Do you know which Kernel config option is needed for IPV6 NAT?

@franciscofranco I found one resource:
https://review.lineageos.org/c/LineageOS/android_kernel_oneplus_msm8998/+/231287/1/arch/arm64/configs/lineage_oneplus5_defconfig#904

According to this (between others):

CONFIG_NF_NAT_IPV6=y
CONFIG_NF_NAT_MASQUERADE_IPV6=y
CONFIG_IP6_NF_NAT=y
CONFIG_IP6_NF_TARGET_MASQUERADE=y

**Comment by ghost** [comment]
Hey @franciscofranco ,

I don't wanna be rude (I know everyone hates those attention seeking mentions) but just wanna make sure you got my last message here as I'm pretty sure you get tons of messages daily xD

**Comment by franciscofranco** [comment]
I did. I'll update the kernel this weekend ;)

**Comment by ghost** [comment]
Perfect ❤️
![Screenshot_20190511-091634](https://user-images.githubusercontent.com/3320229/57565862-c14c3e00-73cd-11e9-955b-f08ddfb54b39.jpg)

**Comment by franciscofranco** [comment]
:)
